name = "next-hono-redisdb"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AU2PAAIjcDFkZWFlMGFkZDQ5ODU0MWUxYTMyYWM5MmM5NDkwODlkNnAxMA"
UPSTASH_REDIS_REST_URL = "https://welcome-glider-19855.upstash.io"