import prisma from '../../lib/prisma';
import Link from 'next/link'
import React from 'react'
import { getPostCached } from '../../lib/postCache';

export const metadata = {
    title: "Bloks Layout",
    description: "Generated by create next app",
  };

async function Blogs() {
    const blogs = await getPostCached(); 
    // const blogs = await prisma.post.findMany(); 
    // console.log(blog[0])
    // const blogs = [{
    //     id: 1,
    //     title: 'Blog 1',
    //     descriptins: "blog 1 description"
    // },
    // {
    //     id: 2,
    //     title: 'Blog 2',
    //     descriptins: "blog 2 description"
    // },
    // {
    //     id: 3,
    //     title: 'Blog 3',
    //     descriptins: "blog 3 description"
    // }]
    return (
        <main>
            <p className='text-lg font-bold p-2'>Posts From MongoDB</p>
            <ul>
                {blogs.map((blog)=>(
                    <li className='p-4 border my-2' key={blog.id} blog={blog}><Link href={`/blogs/${blog.id}`}>{blog.title}</Link></li>
                ))}
            </ul>
        </main>
    )
}

export default Blogs
