
import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "@/provider/Theme-Provider";
import { Toaster } from "@/components/ui/sonner";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={` antialiase`}
      >
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
         >
        {children}
        <Toaster 
         position="top-center"
        />
        </ThemeProvider>
      </body>
    </html>
  );
}
